language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.7"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment -c conda-forge python=$TRAVIS_PYTHON_VERSION fenics==2019.1.0 muq seaborn statsmodels
  - conda activate test-environment
  - git clone --depth 1 --branch 3.0.0 https://github.com/hippylib/hippylib.git
  - python hippylib/setup.py install
  - python setup.py install

script:
  cd hippylib2muq/test/ && python -m unittest discover -v
